### PR TITLE
refactor(core): Better typescript support

### PR DESCRIPTION
**Pull request by Myphz**
- Added a better tsconfig
- Fixed all typescript errors in core/index.ts
- Use narrower types, avoid `any`s

This PR should not affect the logic whatsoever. It should improve the DX for TypeScript users.

### CODE REVIEW

**Comment by feledori** [comment]
hey, thanks for taking the time on this! i am not sure we want to have all the typescript guards in the implementation. The typescript types are important for the api consumer not internals. a good choice may be defining types in a d.ts and leaving the core in js with jsdoc. I don't think @clementroche would like to use type guard like isHTMLElement. Will look review it closer when I have time for it. thanks tho.

**Comment by clementroche** [comment]
hello @Myphz, thank you for your PR however i've just merged the snap branch into main. Can you adapt your PR accordingly ?

**Comment by Myphz** [comment]
> hey, thanks for taking the time on this! i am not sure we want to have all the typescript guards in the implementation. The typescript types are important for the api consumer not internals. a good choice may be defining types in a d.ts and leaving the core in js with jsdoc. I don't think @clementroche would like to use type guard like isHTMLElement. Will look review it closer when I have time for it. thanks tho.

Thanks for your feedback. My changes were mostly on the `index.ts` file and the `Lenis` class definition, which I believe is what is consumed by the APIs, not internally. Since that file was already using TypeScript, I figured it'd be helpful to add good type definitions to it. I didn't touch any other JavaScript file.

I will soon update the PR for the latest update. Let me know if there's a better way to handle this task. Thank you!

**Comment by feledori** [comment]
> > hey, thanks for taking the time on this! i am not sure we want to have all the typescript guards in the implementation. The typescript types are important for the api consumer not internals. a good choice may be defining types in a d.ts and leaving the core in js with jsdoc. I don't think @clementroche would like to use type guard like isHTMLElement. Will look review it closer when I have time for it. thanks tho.
> 
> Thanks for your feedback. My changes were mostly on the `index.ts` file and the `Lenis` class definition, which I believe is what is consumed by the APIs, not internally. Since that file was already using TypeScript, I figured it'd be helpful to add good type definitions to it. I didn't touch any other JavaScript file.
> 
> I will soon update the PR for the latest update. Let me know if there's a better way to handle this task. Thank you!

yeah, makes sense. maybe a seperate d.ts file would make more sense. will have to talk this over. types seem mostly sound as far I can tell from the quick glance i took. good job.

**Comment by Myphz** [comment]
I've updated the PR to the latest branch. This time, I made some changes to the Lenis class to simplify it a bit:

- Removed `userData` parameter and `this.userData` (apparently it was useless - it was never assigned)
- `this.isTouching` removed (it was assigned but it was never used)
- Removed `this.hasScrolled` (it was used but never assigned, so it always resulted in `undefined` - the assignment was commented)

I may be wrong on these assumptions though - let me know your thoughts. Thanks

**Comment by clementroche** [comment]
userData is necessary

**Comment by Myphz** [comment]
> userData is necessary

fixed

**Comment by clementroche** [comment]
Thank you @Myphz, I will not merge your PR but use it as a base for improving types step by step to be sure that it doesn't break nothing and that I understand every choice you've made.

**Comment by feledori** [comment]
closing this in favour of #369. Thanks for the initial setup!

**Pull request closed without merging**
