### PR TITLE
fix: add lenis-svelte to the list of plugins

### PR DESCRIPTION
**Pull request by DaniAcu**
I'm started working on svelte, and I notice lenis doesn't have a wrapper for svelte like it does for nuxt and vue. So I create the package.

If you are okay with adding this package here it will be really helpful for future svelte developer that are trying to use this awesome library in their projects.

### CODE REVIEW

**Comment by clementroche** [comment]
Thanks @DaniAcu, what do you think about working on `lenis/svelte` ?

**Comment by DaniAcu** [comment]
@clementroche do you mean inside this package? It will be great, I could create another PR to move the lib here.

I have a couple questions, 
- can I still add me as an author in the package.json?
- I will be not having a svelte playground to show use cases, do you prefer that I add a public codesandbox for that and add it to the documentation?
- How the publish version of lenis/svelte will works? You are doing it manually, I can be able to push a new version from my own?

**Comment by clementroche** [comment]
- yes, we could add you as `contributors` https://docs.npmjs.com/cli/v10/configuring-npm/package-json#people-fields-author-contributors
- as you want as long as it's located into `/packages/svelte`
- we only allow our internal team to publish new versions for security reasons so you'll have to PR first.

**Comment by DaniAcu** [comment]
Okay, I will move the package here. Do you want to have any other framework wrapper?

**Comment by clementroche** [comment]
vue

**Comment by richhost** [comment]
Hello, I have created a Svelte5 binding as a preview for future versions. https://github.com/richhost/svelte-lenis

**Comment by DaniAcu** [comment]
Sorry for the delay @clementroche I will close this PR in favor of this https://github.com/darkroomengineering/lenis/pull/390.

**Pull request closed without merging**
