### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by meesrutten**
Add Framer Motion implementation.

Let me know if anything needs to change!

### CODE REVIEW

**Comment by clementroche** [comment]
Thank you for this PR. However i think that this example should use `lenis/react`.

**Comment by feledori** [comment]
Agree with @clementroche, as most people using lenis with react will use lenis/react. React lenis will setup a rAF for itself so it has to be explicitly disabled with the autoRaf prop on the Provider. This is currently a discrepancy between lenis core and lenis react.

**Comment by clementroche** [comment]
I'll probably wait until we find a proper solution about rAFs

**Comment by clementroche** [comment]
Thank you @meesrutten I added this example to `lenis/react` documentation:

https://github.com/darkroomengineering/lenis/blob/main/packages/react/README.md#framer-motion-integration

**Pull request closed without merging**
